#!/usr/bin/env python3
"""Regenerate the *derived* documentation pages.

``docs/04_api_reference.md`` and ``docs/05_database_schema.md`` are generated from the application
itself - the OpenAPI schema for the endpoints and the SQLAlchemy metadata for the tables - so they
cannot drift away from the code.  Run it after adding an endpoint or a column:

    python3 docs/make_docs.py

The narrative pages (overview, architecture, pipeline, methods, testing, limitations) are written by
hand and are *not* touched by this script.
"""
from __future__ import annotations

import datetime as _dt
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from backend.app.main import create_app                       # noqa: E402
from backend.app import models as models_mod                   # noqa: E402

STAMP = "<!-- generated by docs/make_docs.py - do not edit by hand -->"
GROUPS = ["system", "files", "analysis", "modules", "generator", "benchmark", "reports", "docs"]


def api_doc() -> str:
    app = create_app()
    spec = app.openapi()
    paths = spec.get("paths", {})
    tag_of = {}
    for path, item in paths.items():
        for method, op in item.items():
            if not isinstance(op, dict):
                continue
            for tag in op.get("tags") or ["untagged"]:
                tag_of.setdefault(tag, []).append((path, method.upper(), op))

    lines = [STAMP, "<!-- summary: Complete REST reference generated from the running OpenAPI schema -->",
             "# API reference", "",
             f"Generated {_dt.date.today().isoformat()} from the FastAPI application itself: "
             f"**{len(paths)} paths**, **{sum(len([m for m in v if isinstance(v[m], dict)]) for v in paths.values())} operations**.",
             "",
             "Interactive documentation: [Swagger UI](/docs) and [ReDoc](/redoc); the machine-readable "
             "schema is at [/openapi.json](/openapi.json).",
             "",
             "## Conventions used by every endpoint", "",
             "* `x-session-id` header isolates files, analyses, reports and generated signals per browser session.",
             "* Long-running work (`POST /api/analyze`, `POST /api/blind-analysis`, `POST /api/benchmark`) "
             "returns a job immediately; poll `GET /api/jobs/{job_id}` for `progress`/`stage_message` and "
             "`DELETE`/`POST /api/jobs/{job_id}/cancel` to abort.",
             "* Measured quantities are returned as `{value, unit, confidence, method, evidence, status}`. "
             "When an estimator cannot support a number it returns `status=\"unable\"` with `value=null` and "
             "a reason - the platform never invents a parameter.",
             "* Modulation, FEC, interleaving and protocol statements are **hypotheses**: ranked candidates, "
             "confidence, evidence and an explicit limitations list.",
             "",
             "## Endpoint map", ""]
    order = GROUPS + [t for t in tag_of if t not in GROUPS]
    for tag in order:
        items = tag_of.get(tag)
        if not items:
            continue
        lines += [f"### {tag}", "", "| Method | Path | Summary |", "| --- | --- | --- |"]
        for path, method, op in sorted(items, key=lambda x: (x[0], x[1])):
            summary = (op.get("summary") or "").replace("|", "\\|")
            lines.append(f"| `{method}` | `{path}` | {summary} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def db_doc() -> str:
    from sqlalchemy import inspect as sa_inspect
    tables = []
    for name, table in models_mod.Base.metadata.tables.items():
        cols = []
        for col in table.columns:
            fks = ", ".join(f"{fk.column.table.name}.{fk.column.name}" for fk in col.foreign_keys)
            cols.append((col.name, str(col.type), "yes" if col.primary_key else "", fks,
                         "yes" if not col.nullable else ""))
        tables.append((name, cols))
    lines = [STAMP, "<!-- summary: Relational schema - which measured value is stored where, and what is deliberately not stored -->",
             "# Database schema", "",
             f"Generated {_dt.date.today().isoformat()} from the SQLAlchemy models "
             f"(`backend/app/models.py`): **{len(tables)} tables**. SQLite by default "
             "(`SIH_DATABASE_URL`), PostgreSQL compatible (the same models, no SQLite-specific types).",
             "",
             "**Design rule: no raw IQ arrays in the relational tables.** Samples are streamed to disk in "
             "`data/uploads`, and the analysis result (downsampled spectrum/waterfall, symbol decisions, "
             "previews) is written to a compressed cache file next to the analysis record. The database "
             "stores queryable *metadata* only - parameters, hypotheses, confidences, evidence, bit "
             "statistics - so history, comparison and reporting are pure SQL.", ""]
    for name, cols in tables:
        lines += [f"## `{name}`", "", "| Column | Type | PK | References | Nullable |", "| --- | --- | --- | --- | --- |"]
        for cname, ctype, pk, fks, nullable in cols:
            lines.append(f"| `{cname}` | `{ctype}` | {pk} | {fks} | {nullable} |")
        lines.append("")
    lines += ["## Where the big arrays live", "",
              "| Data | Location |", "| --- | --- |",
              "| raw samples | `data/uploads/<uuid>.<ext>` (streamed, size-capped) |",
              "| generated signals | `data/generated/<uuid>.<ext>` + ground truth JSON in the row |",
              "| full analysis result | `data/cache/<analysis_id>.json.gz` (charts, symbols, previews) |",
              "| reports | `data/reports/<uuid>.pdf\\|json\\|csv\\|txt` |", ""]
    return "\n".join(lines) + "\n"


def main() -> None:
    for filename, text in (("04_api_reference.md", api_doc()), ("05_database_schema.md", db_doc())):
        path = os.path.join(ROOT, "docs", filename)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote docs/{filename} ({len(text)} chars)")


if __name__ == "__main__":
    main()
